using UnityEngine;

public class StandUpCollider : MonoBehaviour
{
    public bool ispushing;
    
    private void OnTriggerEnter(Collider other)
    {
        IceBlockPush block =  other.gameObject.GetComponent<IceBlockPush>();
        if (block != null)
        {
            ispushing = true;
        }
    }
        
    private void OnTriggerExit(Collider other)
    {
        IceBlockPush block =  other.gameObject.GetComponent<IceBlockPush>();
        if (block != null)
        {
            ispushing = false;
        }
    }
}
