using System;
using UnityEngine;

public class Pit : MonoBehaviour
{
   public PlayerMove player;
   public IceBlockPush ice;
   //
   //  // Update is called once per frame
   //  void Update()
   //  {
   //      if (Input.GetKeyDown(KeyCode.Space))
   //      {
   //          player.Reset();
   //          ice.Reset();
   //      }
   //  }

   private void OnTriggerEnter(Collider other)
   {
      if (other.GetComponent<PlayerMove>())
      {
         player.Reset();
      }
      else if(other.GetComponent<IceBlockPush>())
      {
         ice.Reset();
      }
   }
}
